# Generated by Django 6.0 on 2026-01-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('profile_url', models.URLField()),
                ('icon', models.ImageField(upload_to='system_settings/social_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='favicon',
            field=models.ImageField(upload_to='system_settings/general_settings/favicons/'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='logo',
            field=models.ImageField(upload_to='system_settings/general_settings/logos/'),
        ),
    ]
