# Generated by Django 6.0 on 2026-01-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('landing', 'Landing Page'), ('about', 'About Us'), ('services', 'Services'), ('contact', 'Contact Us'), ('blog', 'Blog')], max_length=100, unique=True),
        ),
    ]
