# Generated by Django 6.0 on 2026-01-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_page_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
